# Bài tập thực hành tuần 2
> Họ và tên: Nguyễn Vạn Phúc Huy <br>
> MSSV: 23110163 <br>
> Lớp: 23TTH (Chiều thứ 6, ca 1)

In [46]:
# copy paste từ tuần 1 =)))
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import StandardScaler, KBinsDiscretizer
from sklearn.decomposition import PCA

### 1. Khoảng cách giữa các điểm trong dữ liệu số

Trước hết, chúng ta sẽ lấy dữ liệu từ file `ionosphere.data` trực tiếp theo đường link dưới đây.

In [47]:
link_hd_ko_che= r'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'
df = pd.read_csv(link_hd_ko_che, header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

Sau đó thực hiện lấy thông tin đặc trưng của bộ dữ liệu bằng hàm `describe()` và hàm `info()` của pandas.

In [48]:
display(df.info())
display(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       351 non-null    int64
 1   1       351 non-null    int64
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22      351 non-null    float64
 23  23      351 non-null    float64
 24  24      351 non-null    float64
 25  25      351 non-null    float64
 26  26      351 non-null    float64
 27  27      351 non-null    float64
 28  28      351 non-null    float64
 29  29      351 non-null    float64
 30  30      351 non-null    float64
 31  31      351 non-null    float64
 32  32      351 non-null    float64
 33  33      351 non-null    float64
 34  34      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

None

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
count,351.000000,351.0,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.891738,0.0,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,...,0.396135,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480
std,0.311155,0.0,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,...,0.578451,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337
min,0.000000,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,1.000000,0.0,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,...,0.000000,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350
50%,1.000000,0.0,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,...,0.553890,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000
75%,1.000000,0.0,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,...,0.905240,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Bỏ cột cuối (vì yêu cầu trong file thực hành nó vậy)

In [49]:
df.pop(df.columns[-1])
df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,0.95378,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.94520,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.93988,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,0.91050,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,0.86467,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151

Khởi tạo các điểm point1, point2, point3 tương ướng là dòng 0, 1, 2 của array và tính chuẩn p = 1, 2, inf.

In [50]:
array = df.values
print(array)

point1 = array[0, :]
point2 = array[1, :]
point3 = array[2, :]

# p = 1
dist01_2 = np.linalg.norm(point1 - point2, 1)
dist01_3 = np.linalg.norm(point1 - point3, 1)

# p = 2
dist1_2 = np.linalg.norm(point1 - point2)
dist1_3 = np.linalg.norm(point1 - point3)

# p = inf 
dist11_2 = np.linalg.norm(point1 - point2, np.inf)
dist11_3 = np.linalg.norm(point1 - point3, np.inf)


print(dist1_2)
print(dist1_3)
print(dist01_2)
print(dist01_3)
print(dist11_2)
print(dist11_3)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
2.7763589251571923
1.1697276018372824
13.080950000000001
5.359709999999999
1.12221
0.45772

#### Viết hàm tính các chuẩn p = 1, 2, inf cho 50 dòng đầu tiên của array trong mục 1

In [51]:
def calculate_distances(array):
    distances = []
    for i in range(50):
        for j in range(i + 1, 50):
            point_i = array[i, :]
            point_j = array[j, :]
            dist_p1 = np.linalg.norm(point_i - point_j, 1)
            dist_p2 = np.linalg.norm(point_i - point_j, 2)
            dist_pinf = np.linalg.norm(point_i - point_j, np.inf)
            distances.append((i, j, dist_p1, dist_p2, dist_pinf))
    return distances




distances = calculate_distances(array)
for dist in distances:
    print(f"Distance between point {dist[0]} and point {dist[1]}: p=1: {dist[2]}, p=2: {dist[3]}, p=inf: {dist[4]}")

Distance between point 0 and point 1: p=1: 13.080950000000001, p=2: 2.7763589251571923, p=inf: 1.12221
Distance between point 0 and point 2: p=1: 5.359709999999999, p=2: 1.1697276018372824, p=inf: 0.45772
Distance between point 0 and point 3: p=1: 21.057290000000002, p=2: 4.772562679724594, p=inf: 1.6053600000000001
Distance between point 0 and point 4: p=1: 6.21387, p=2: 1.3773473382919792, p=inf: 0.53525
Distance between point 0 and point 5: p=1: 15.166310000000001, p=2: 3.049072399681582, p=inf: 0.97202
Distance between point 0 and point 6: p=1: 7.577039999999999, p=2: 1.530471119753653, p=inf: 0.48305
Distance between point 0 and point 7: p=1: 22.28699, p=2: 4.803640361215647, p=inf: 1.85243
Distance between point 0 and point 8: p=1: 5.81361, p=2: 1.2050178826473905, p=inf: 0.39934000000000003
Distance between point 0 and point 9: p=1: 17.20169, p=2: 3.5643139959184293, p=inf: 1.3090600000000001
Distance between point 0 and point 10: p=1: 7.06033, p=2: 1.5055474137668332, p=inf: 0.49585
Distance between point 0 and point 11: p=1: 16.25809, p=2: 3.584335524989255, p=inf: 1.47357
Distance between point 0 and point 12: p=1: 6.372240000000001, p=2: 1.3487913315261186, p=inf: 0.46086000000000005
Distance between point 0 and point 13: p=1: 14.074530000000001, p=2: 3.1139951292672245, p=inf: 1.42915
Distance between point 0 and point 14: p=1: 14.98318, p=2: 3.102336605818266, p=inf: 0.92012
Distance between point 0 and point 15: p=1: 18.11757, p=2: 3.851302322007453, p=inf: 1.6053600000000001
Distance between point 0 and point 16: p=1: 10.9936, p=2: 2.2606501964257983, p=inf: 0.70417
Distance between point 0 and point 17: p=1: 34.53319, p=2: 6.7281216338514565, p=inf: 2.0
Distance between point 0 and point 18: p=1: 12.67162, p=2: 2.739830121704628, p=inf: 0.9122399999999999
Distance between point 0 and point 19: p=1: 30.185820000000003, p=2: 6.0044294406213155, p=inf: 1.84356
Distance between point 0 and point 20: p=1: 6.24754, p=2: 1.4768651825403698, p=inf: 0.59114
Distance between point 0 and point 21: p=1: 30.92729, p=2: 6.163734316134984, p=inf: 2.0
Distance between point 0 and point 22: p=1: 7.7604299999999995, p=2: 1.624263827738585, p=inf: 0.54472
Distance between point 0 and point 23: p=1: 27.62719, p=2: 5.68832319052812, p=inf: 2.0
Distance between point 0 and point 24: p=1: 6.265499999999999, p=2: 1.386334658587168, p=inf: 0.5182800000000001
Distance between point 0 and point 25: p=1: 16.24697, p=2: 3.2079882195388434, p=inf: 1.0376
Distance between point 0 and point 26: p=1: 8.25909, p=2: 1.784492093145834, p=inf: 0.67808
Distance between point 0 and point 27: p=1: 25.77937, p=2: 5.358255846812468, p=inf: 1.99539
Distance between point 0 and point 28: p=1: 21.26855, p=2: 4.768385153959357, p=inf: 1.54487
Distance between point 0 and point 29: p=1: 27.856350000000003, p=2: 5.6610353045975605, p=inf: 2.0
Distance between point 0 and point 30: p=1: 8.44451, p=2: 1.9646133598497186, p=inf: 0.81359
Distance between point 0 and point 31: p=1: 20.84771, p=2: 4.389375054799943, p=inf: 1.54487
Distance between point 0 and point 32: p=1: 4.18114, p=2: 0.8691547915072435, p=inf: 0.29203999999999997
Distance between point 0 and point 33: p=1: 10.570170000000001, p=2: 2.636364973803893, p=inf: 1.4494500000000001
Distance between point 0 and point 34: p=1: 11.94792, p=2: 2.5758184746988673, p=inf: 1.07859
Distance between point 0 and point 35: p=1: 19.761910000000004, p=2: 4.020352814554961, p=inf: 1.36528
Distance between point 0 and point 36: p=1: 8.78373, p=2: 1.8330642644762896, p=inf: 0.6522600000000001
Distance between point 0 and point 37: p=1: 29.15677, p=2: 5.897289268799692, p=inf: 1.85243
Distance between point 0 and point 38: p=1: 10.47754, p=2: 2.172253563790379, p=inf: 0.6524099999999999
Distance between point 0 and point 39: p=1: 12.92207, p=2: 3.003011072024211, p=inf: 1.453
Distance between point 0 and point 40: p=1: 15.50779, p=2: 3.7555108229240934, p=inf: 1.27175
Distance between point 0 and point 41: p=1: 26.848529999999997, p=2: 5.654889629241228, p=inf: 1.99539
Distance between point 0 and point 42: p=1: 15.406070000000001, p=2: 3.4276336797125797, p=inf: 1.13039
Distance between point 0 and point 43: p=1: 19.812210000000004, p=2: 4.300753501573881, p=inf: 1.63825
Distance between point 0 and point 44: p=1: 6.320250000000001, p=2: 1.3083248824737685, p=inf: 0.41263000000000005
Distance between point 0 and point 45: p=1: 22.58643, p=2: 4.656229775247351, p=inf: 1.58212
Distance between point 0 and point 46: p=1: 6.06466, p=2: 1.4426177832676264, p=inf: 0.60167
Distance between point 0 and point 47: p=1: 15.984620000000001, p=2: 3.744958276563305, p=inf: 1.85243
Distance between point 0 and point 48: p=1: 7.74504, p=2: 1.590902529132442, p=inf: 0.5728000000000001
Distance between point 0 and point 49: p=1: 21.060719999999996, p=2: 4.400934784474772, p=inf: 1.6053600000000001
Distance between point 1 and point 2: p=1: 15.80038, p=2: 3.3800330447497107, p=inf: 1.10868
Distance between point 1 and point 3: p=1: 20.7696, p=2: 4.454509355899929, p=inf: 1.453
Distance between point 1 and point 4: p=1: 11.52616, p=2: 2.5405313555238793, p=inf: 1.0297399999999999
Distance between point 1 and point 5: p=1: 12.58796, p=2: 2.7838831970109665, p=inf: 1.02959
Distance between point 1 and point 6: p=1: 12.281089999999999, p=2: 2.7539302391854448, p=inf: 1.26313
Distance between point 1 and point 7: p=1: 22.639000000000003, p=2: 4.859195725220379, p=inf: 1.62237
Distance between point 1 and point 8: p=1: 16.54506, p=2: 3.4724946124940206, p=inf: 1.42077
Distance between point 1 and point 9: p=1: 14.54198, p=2: 3.2714733205392337, p=inf: 1.36117
Distance between point 1 and point 10: p=1: 16.563000000000002, p=2: 3.4588373100219676, p=inf: 1.4239600000000001
Distance between point 1 and point 11: p=1: 23.70878, p=2: 5.073432244723487, p=inf: 1.69707
Distance between point 1 and point 12: p=1: 17.698970000000003, p=2: 3.7733247031894828, p=inf: 1.45404
Distance between point 1 and point 13: p=1: 21.918319999999998, p=2: 4.540862974215364, p=inf: 1.51685
Distance between point 1 and point 14: p=1: 24.348249999999997, p=2: 4.871305851853279, p=inf: 1.51685
Distance between point 1 and point 15: p=1: 12.67514, p=2: 2.9013132908047004, p=inf: 1.18805
Distance between point 1 and point 16: p=1: 20.26597, p=2: 4.175570937309052, p=inf: 1.4589699999999999
Distance between point 1 and point 17: p=1: 36.99534, p=2: 7.017636574802089, p=inf: 2.0
Distance between point 1 and point 18: p=1: 19.97037, p=2: 3.9776427486263772, p=inf: 1.41224
Distance between point 1 and point 19: p=1: 30.94441, p=2: 5.969001458242408, p=inf: 2.0
Distance between point 1 and point 20: p=1: 17.831650000000003, p=2: 3.9084401599231375, p=inf: 1.51685
Distance between point 1 and point 21: p=1: 26.03694, p=2: 5.344618143141753, p=inf: 2.0
Distance between point 1 and point 22: p=1: 16.78962, p=2: 3.612240492215323, p=inf: 1.39219
Distance between point 1 and point 23: p=1: 29.96502, p=2: 6.035210277695384, p=inf: 2.0
Distance between point 1 and point 24: p=1: 17.14547, p=2: 3.7622455614034553, p=inf: 1.45077
Distance between point 1 and point 25: p=1: 22.28624, p=2: 4.658342934306146, p=inf: 1.51685
Distance between point 1 and point 26: p=1: 16.122320000000002, p=2: 3.494229059377762, p=inf: 1.39622
Distance between point 1 and point 27: p=1: 24.57698, p=2: 5.067302102302565, p=inf: 2.0
Distance between point 1 and point 28: p=1: 30.633620000000004, p=2: 6.0079292632819845, p=inf: 1.95099
Distance between point 1 and point 29: p=1: 31.388079999999995, p=2: 6.1176207054703875, p=inf: 2.0
Distance between point 1 and point 30: p=1: 20.0428, p=2: 4.331195102578502, p=inf: 1.51685
Distance between point 1 and point 31: p=1: 24.962780000000002, p=2: 5.202146473754849, p=inf: 1.62237
Distance between point 1 and point 32: p=1: 15.47241, p=2: 3.2536361298553342, p=inf: 1.3380100000000001
Distance between point 1 and point 33: p=1: 18.6186, p=2: 4.146310474361513, p=inf: 1.69707
Distance between point 1 and point 34: p=1: 21.13621, p=2: 4.465606714378238, p=inf: 1.28522
Distance between point 1 and point 35: p=1: 25.97102, p=2: 5.401781547341581, p=inf: 1.78036
Distance between point 1 and point 36: p=1: 18.69414, p=2: 4.1204922206697585, p=inf: 1.48946
Distance between point 1 and point 37: p=1: 27.8386, p=2: 5.633787633200243, p=inf: 2.0
Distance between point 1 and point 38: p=1: 19.80253, p=2: 4.081736453802475, p=inf: 1.43733
Distance between point 1 and point 39: p=1: 21.84682, p=2: 4.3622179087248725, p=inf: 1.41003
Distance between point 1 and point 40: p=1: 22.703500000000002, p=2: 4.7064892360442085, p=inf: 1.62999
Distance between point 1 and point 41: p=1: 26.61692, p=2: 5.5594263374380635, p=inf: 2.0
Distance between point 1 and point 42: p=1: 20.28314, p=2: 4.178255657065518, p=inf: 1.43601
Distance between point 1 and point 43: p=1: 26.211460000000002, p=2: 5.367569491622815, p=inf: 1.64286
Distance between point 1 and point 44: p=1: 17.3333, p=2: 3.605786209330775, p=inf: 1.41497
Distance between point 1 and point 45: p=1: 19.992359999999998, p=2: 4.2578128887963125, p=inf: 1.67743
Distance between point 1 and point 46: p=1: 17.971229999999995, p=2: 3.889479524807914, p=inf: 1.46973
Distance between point 1 and point 47: p=1: 17.53049, p=2: 3.9049206328554233, p=inf: 1.93035
Distance between point 1 and point 48: p=1: 17.89603, p=2: 3.914337553750315, p=inf: 1.4505400000000002
Distance between point 1 and point 49: p=1: 18.960350000000002, p=2: 3.966208782439472, p=inf: 1.63147
Distance between point 2 and point 3: p=1: 20.30478, p=2: 4.671267441562301, p=inf: 1.75535
Distance between point 2 and point 4: p=1: 8.50424, p=2: 1.8385075847545476, p=inf: 0.66143
Distance between point 2 and point 5: p=1: 14.248440000000002, p=2: 3.129187057815496, p=inf: 1.09924
Distance between point 2 and point 6: p=1: 11.57535, p=2: 2.3996959590123077, p=inf: 0.69877
Distance between point 2 and point 7: p=1: 21.16584, p=2: 4.67950618020748, p=inf: 1.75535
Distance between point 2 and point 8: p=1: 7.8223, p=2: 1.6954603740577365, p=inf: 0.5748
Distance between point 2 and point 9: p=1: 16.08502, p=2: 3.4523357405965025, p=inf: 1.20908
Distance between point 2 and point 10: p=1: 9.69796, p=2: 2.178437583911919, p=inf: 0.68482
Distance between point 2 and point 11: p=1: 15.70286, p=2: 3.410118581750494, p=inf: 1.27502
Distance between point 2 and point 12: p=1: 6.700950000000001, p=2: 1.424694493251097, p=inf: 0.51429
Distance between point 2 and point 13: p=1: 11.98718, p=2: 2.642947666413393, p=inf: 1.12608
Distance between point 2 and point 14: p=1: 10.30557, p=2: 2.2493321918516167, p=inf: 0.8494999999999999
Distance between point 2 and point 15: p=1: 18.0406, p=2: 3.9063530870877505, p=inf: 1.5459100000000001
Distance between point 2 and point 16: p=1: 6.22373, p=2: 1.4121107012199858, p=inf: 0.53632
Distance between point 2 and point 17: p=1: 33.6223, p=2: 6.604433214939796, p=inf: 2.0
Distance between point 2 and point 18: p=1: 9.88059, p=2: 2.1011811832157643, p=inf: 0.80189
Distance between point 2 and point 19: p=1: 27.627850000000002, p=2: 5.659730252238175, p=inf: 1.83775
Distance between point 2 and point 20: p=1: 5.71581, p=2: 1.2467806228442917, p=inf: 0.52675
Distance between point 2 and point 21: p=1: 30.896880000000003, p=2: 6.294934319800326, p=inf: 1.88965
Distance between point 2 and point 22: p=1: 3.4706600000000005, p=2: 0.8463991636338023, p=inf: 0.38056
Distance between point 2 and point 23: p=1: 26.544720000000005, p=2: 5.6090942308540335, p=inf: 2.0
Distance between point 2 and point 24: p=1: 3.7261100000000003, p=2: 0.9022338191954457, p=inf: 0.38800999999999997
Distance between point 2 and point 25: p=1: 17.644219999999997, p=2: 3.636242130799323, p=inf: 1.05346
Distance between point 2 and point 26: p=1: 11.044880000000001, p=2: 2.4725147600772783, p=inf: 0.9146
Distance between point 2 and point 27: p=1: 25.93152, p=2: 5.6104552480703385, p=inf: 2.0
Distance between point 2 and point 28: p=1: 16.650620000000004, p=2: 3.9616174261278685, p=inf: 1.4022000000000001
Distance between point 2 and point 29: p=1: 28.197380000000003, p=2: 5.808459183862791, p=inf: 2.0
Distance between point 2 and point 30: p=1: 8.84, p=2: 1.8522787284855375, p=inf: 0.58455
Distance between point 2 and point 31: p=1: 19.49584, p=2: 4.193640817547444, p=inf: 1.38238
Distance between point 2 and point 32: p=1: 5.39883, p=2: 1.2118215066172082, p=inf: 0.42489
Distance between point 2 and point 33: p=1: 10.468040000000002, p=2: 2.6333550013623306, p=inf: 1.20232
Distance between point 2 and point 34: p=1: 10.09461, p=2: 2.108558972355291, p=inf: 0.7927599999999999
Distance between point 2 and point 35: p=1: 17.79122, p=2: 3.692832402262524, p=inf: 1.25577
Distance between point 2 and point 36: p=1: 4.7322, p=2: 1.143112945863181, p=inf: 0.5143
Distance between point 2 and point 37: p=1: 26.938280000000002, p=2: 5.618223748712754, p=inf: 1.83775
Distance between point 2 and point 38: p=1: 5.85357, p=2: 1.312886167685531, p=inf: 0.51519
Distance between point 2 and point 39: p=1: 8.69736, p=2: 2.2666846051447034, p=inf: 1.38238
Distance between point 2 and point 40: p=1: 13.48098, p=2: 3.083444406666026, p=inf: 1.12302
Distance between point 2 and point 41: p=1: 26.1244, p=2: 5.5302454197440465, p=inf: 2.0
Distance between point 2 and point 42: p=1: 13.661180000000002, p=2: 2.8926806603218407, p=inf: 1.05977
Distance between point 2 and point 43: p=1: 18.894579999999998, p=2: 4.125918921355581, p=inf: 1.64286
Distance between point 2 and point 44: p=1: 7.539000000000001, p=2: 1.696884359289106, p=inf: 0.5798800000000001
Distance between point 2 and point 45: p=1: 22.89582, p=2: 4.897846015403098, p=inf: 1.75535
Distance between point 2 and point 46: p=1: 5.522069999999999, p=2: 1.1804877080681526, p=inf: 0.44488999999999995
Distance between point 2 and point 47: p=1: 15.881610000000002, p=2: 3.827552030044791, p=inf: 2.0
Distance between point 2 and point 48: p=1: 4.16871, p=2: 0.9706709908614761, p=inf: 0.42871999999999993
Distance between point 2 and point 49: p=1: 19.98939, p=2: 4.355859915940824, p=inf: 1.5459100000000001
Distance between point 3 and point 4: p=1: 20.752180000000003, p=2: 4.728258559406412, p=inf: 1.65697
Distance between point 3 and point 5: p=1: 17.81826, p=2: 3.8532892207307774, p=inf: 1.11949
Distance between point 3 and point 6: p=1: 24.996350000000003, p=2: 5.509146416142886, p=inf: 1.8251
Distance between point 3 and point 7: p=1: 15.736959999999998, p=2: 3.7546281696860477, p=inf: 1.3933
Distance between point 3 and point 8: p=1: 25.08336, p=2: 5.587566238945182, p=inf: 1.9039199999999998
Distance between point 3 and point 9: p=1: 19.094820000000002, p=2: 4.107967256247304, p=inf: 1.63728
Distance between point 3 and point 10: p=1: 26.54798, p=2: 5.863987869752119, p=inf: 1.9071099999999999
Distance between point 3 and point 11: p=1: 27.239900000000002, p=2: 6.206690805542032, p=inf: 2.0
Distance between point 3 and point 12: p=1: 24.512290000000004, p=2: 5.475426905776389, p=inf: 1.93719
Distance between point 3 and point 13: p=1: 21.12056, p=2: 4.770686310920055, p=inf: 2.0
Distance between point 3 and point 14: p=1: 21.50073, p=2: 4.839148383724145, p=inf: 2.0
Distance between point 3 and point 15: p=1: 17.953979999999998, p=2: 4.11352375400945, p=inf: 2.0
Distance between point 3 and point 16: p=1: 20.56567, p=2: 4.624849222353092, p=inf: 1.94212
Distance between point 3 and point 17: p=1: 41.344899999999996, p=2: 8.003283869300152, p=inf: 2.0
Distance between point 3 and point 18: p=1: 18.56813, p=2: 4.065458452142883, p=inf: 1.78637
Distance between point 3 and point 19: p=1: 25.909050000000004, p=2: 5.535335627141321, p=inf: 2.0
Distance between point 3 and point 20: p=1: 23.793210000000002, p=2: 5.3469888978657885, p=inf: 2.0
Distance between point 3 and point 21: p=1: 22.8263, p=2: 5.355404064363397, p=inf: 2.0
Distance between point 3 and point 22: p=1: 19.899679999999996, p=2: 4.530908101385417, p=inf: 1.87534
Distance between point 3 and point 23: p=1: 27.79156, p=2: 6.12264752313899, p=inf: 2.0
Distance between point 3 and point 24: p=1: 21.602390000000003, p=2: 4.975566372173122, p=inf: 1.93392
Distance between point 3 and point 25: p=1: 32.568439999999995, p=2: 6.898849432927203, p=inf: 2.0
Distance between point 3 and point 26: p=1: 23.79508, p=2: 5.449740185605181, p=inf: 2.0
Distance between point 3 and point 27: p=1: 25.15664, p=2: 6.013810580039913, p=inf: 2.0
Distance between point 3 and point 28: p=1: 21.819580000000002, p=2: 5.036205868627691, p=inf: 2.0
Distance between point 3 and point 29: p=1: 26.945400000000003, p=2: 5.988860717415292, p=inf: 2.0
Distance between point 3 and point 30: p=1: 25.254260000000002, p=2: 5.75894007987581, p=inf: 2.0
Distance between point 3 and point 31: p=1: 21.9113, p=2: 5.152029229886026, p=inf: 2.0
Distance between point 3 and point 32: p=1: 22.96497, p=2: 5.158373618952004, p=inf: 1.82116
Distance between point 3 and point 33: p=1: 22.37266, p=2: 5.151403203671792, p=inf: 2.0
Distance between point 3 and point 34: p=1: 22.443230000000003, p=2: 5.004093537764857, p=inf: 2.0
Distance between point 3 and point 35: p=1: 22.72924, p=2: 5.087224659477897, p=inf: 2.0
Distance between point 3 and point 36: p=1: 22.091760000000004, p=2: 5.080220380987424, p=inf: 1.97261
Distance between point 3 and point 37: p=1: 25.7469, p=2: 5.949579202985704, p=inf: 2.0
Distance between point 3 and point 38: p=1: 20.60847, p=2: 4.588024688741332, p=inf: 1.92048
Distance between point 3 and point 39: p=1: 20.62994, p=2: 4.643174922744135, p=inf: 2.0
Distance between point 3 and point 40: p=1: 19.4386, p=2: 4.24906248763183, p=inf: 1.79555
Distance between point 3 and point 41: p=1: 30.663860000000003, p=2: 6.557932211756996, p=inf: 2.0
Distance between point 3 and point 42: p=1: 18.046860000000002, p=2: 3.776382463972631, p=inf: 1.5762
Distance between point 3 and point 43: p=1: 26.252820000000003, p=2: 5.85728778808076, p=inf: 2.0
Distance between point 3 and point 44: p=1: 25.16296, p=2: 5.652421574458154, p=inf: 1.89812
Distance between point 3 and point 45: p=1: 28.67772, p=2: 5.9725089110523735, p=inf: 2.0
Distance between point 3 and point 46: p=1: 23.381750000000004, p=2: 5.308004312875037, p=inf: 1.95288
Distance between point 3 and point 47: p=1: 19.61183, p=2: 4.729897861698496, p=inf: 2.0
Distance between point 3 and point 48: p=1: 21.73987, p=2: 4.941800140121007, p=inf: 1.93369
Distance between point 3 and point 49: p=1: 22.64283, p=2: 5.213330703983779, p=inf: 2.0
Distance between point 4 and point 5: p=1: 11.782660000000002, p=2: 2.72125040799262, p=inf: 1.04064
Distance between point 4 and point 6: p=1: 6.42595, p=2: 1.4333535012340817, p=inf: 0.55828
Distance between point 4 and point 7: p=1: 22.27638, p=2: 4.871716755539057, p=inf: 1.65158
Distance between point 4 and point 8: p=1: 9.060740000000001, p=2: 2.0134162098284594, p=inf: 0.8182
Distance between point 4 and point 9: p=1: 14.0794, p=2: 3.156991381141228, p=inf: 1.03762
Distance between point 4 and point 10: p=1: 10.21672, p=2: 2.0291898613978927, p=inf: 0.64663
Distance between point 4 and point 11: p=1: 19.779259999999997, p=2: 4.149399426808656, p=inf: 1.5287899999999999
Distance between point 4 and point 12: p=1: 9.486170000000001, p=2: 2.2763136697081094, p=inf: 0.80794
Distance between point 4 and point 13: p=1: 17.99574, p=2: 3.8672772000207067, p=inf: 1.48001
Distance between point 4 and point 14: p=1: 18.73183, p=2: 3.9019815080930353, p=inf: 1.12409
Distance between point 4 and point 15: p=1: 16.890340000000002, p=2: 3.7773730540416577, p=inf: 1.57394
Distance between point 4 and point 16: p=1: 14.66491, p=2: 3.0260768689344295, p=inf: 0.82829
Distance between point 4 and point 17: p=1: 33.84703999999999, p=2: 6.463157444020685, p=inf: 1.9414
Distance between point 4 and point 18: p=1: 14.825009999999999, p=2: 3.0530582448259973, p=inf: 1.04608

Do yêu cầu đề bài tập là viết hàm tính các chuẩn p = 1, 2, inf cho 50 dòng đầu tiên của array. Nên trong hàm 'calculate_distances' ta sẽ chạy vòng lặp for để tính khoảng cách giữa array với 50 dòng đầu tiên của array đó. 

```python
for i in range(50):
    for j in range(i + 1, 50):
         ... # Tính khoảng cách giữa dòng i và dòng j
    ...
```

Note: j bắt đầu từ i + 1 để tránh tính khoảng cách giữa một dòng với chính nó và tránh tính lại khoảng cách đã tính trước đó (do khoảng cách giữa dòng i và dòng j là như nhau với khoảng cách giữa dòng j và dòng i).

Tiếp theo chúng ta trích xuất dữ liệu của điểm i và j để tạo thành 2 vector `point_i` và `point_j`:

```python
point_i = array[i]
point_j = array[j]
```
Sau đó, chúng ta sẽ tính khoảng cách giữa `point_i` và `point_j` theo các chuẩn p = 1, 2, inf... bằng cách sử dụng hàm `np.linalg.norm(vector, ord=p)` của NumPy:
Với p = 1 là khoảng cách Manhattan, p = 2 là khoảng cách Euclidean, và p = inf là khoảng cách Chebyshev. Cụ thể:

```python
dist_p1 = np.linalg.norm(point_i - point_j, 1)  # Khoảng cách Manhattan
dist_p2 = np.linalg.norm(point_i - point_j, 2)  # Khoảng cách Euclidean
dist_pinf = np.linalg.norm(point_i - point_j, np.inf)  # Khoảng cách Chebyshev
```

Sau khi tính toán xong thì ta lưu lại vào `distances` để sau này có thể sử dụng hoặc in ra kết quả.

```python
distances.append((i, j, dist_p1, dist_p2, dist_pinf))
```

Cuối cùng ta được hàm `calculate_distances` như yêu cầu:
input: array (dữ liệu đã được xử lý)
output: distances (danh sách chứa khoảng cách giữa các điểm)

### 2. Độ đo tương đồng giữa các điểm trong tập dữ liệu phân loại

Trước hết, chúng ta sẽ lấy dữ liệu từ file `kddcup.data.corrected`

In [52]:
df=pd.read_csv('C:\\Users\\lenovo\\Downloads\\kddcup.data.corrected',header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.00,0.0,0.00,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.00,0.0,0.00,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.00,0.0,0.00,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.00,0.0,0.00,0.0,0.0,normal.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0,tcp,http,SF,212,2288,0,0,0,0,...,255,1.0,0.0,0.33,0.05,0.0,0.01,0.0,0.0,normal.
4898427,0,tcp,http,SF,219,236,0,0,0,0,...,255,1.0,0.0,0.25,0.05,0.0,0.01,0.0,0.0,normal.
4898428,0,tcp,http,SF,218,3610,0,0,0,0,...,255,1.0,0.0,0.20,0.05,0.0,0.01,0.0,0.0,normal.
4898429,0,tcp,http,SF,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.0,0.01,0.0,0.0,normal.
4898430,0,tcp,http,SF,219,1098,0,0,0,0,...,255,1.0,0.0,0.14,0.05,0.0,0.01,0.0,0.0,normal.

Lấy các cột có thuộc tính là `object`

In [53]:
catagorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical columns:", catagorical_columns)
categorical_data = df[catagorical_columns]
print("Categorical data:", categorical_data)

Categorical columns: Index([1, 2, 3, 41], dtype='int64')
Categorical data:           1     2   3        41
0        tcp  http  SF  normal.
1        tcp  http  SF  normal.
2        tcp  http  SF  normal.
3        tcp  http  SF  normal.
4        tcp  http  SF  normal.
...      ...   ...  ..      ...
4898426  tcp  http  SF  normal.
4898427  tcp  http  SF  normal.
4898428  tcp  http  SF  normal.
4898429  tcp  http  SF  normal.
4898430  tcp  http  SF  normal.

[4898431 rows x 4 columns]

Check những giá trị giống nhau và loại bỏ những cột có giá trị giống nhau ở tất cả các dòng (nếu có)

In [54]:
print(categorical_data.duplicated().sum())

df = categorical_data.drop_duplicates()
df

4897822

          1         2     3                 41
0        tcp      http    SF           normal.
1288     tcp      http    S2           normal.
1484     tcp      http    S1           normal.
2062     tcp      smtp    SF           normal.
2067     udp  domain_u    SF           normal.
...      ...       ...   ...               ...
4574130  tcp       bgp   REJ          neptune.
4575586  tcp    Z39_50   REJ          neptune.
4578870  tcp      smtp    SF          neptune.
4579297  tcp     other  RSTO          neptune.
4810949  tcp    telnet  RSTO  buffer_overflow.

[609 rows x 4 columns]

Lấy 100 dòng đầu tiên theo yêu cầu đề bài

In [55]:
df_100 = df.head(100)
df_100

         1         2     3         41
0       tcp      http    SF   normal.
1288    tcp      http    S2   normal.
1484    tcp      http    S1   normal.
2062    tcp      smtp    SF   normal.
2067    udp  domain_u    SF   normal.
...     ...       ...   ...       ...
264244  tcp       ssh    SF  ipsweep.
264361  tcp      smtp  RSTO   normal.
264368  tcp      smtp  RSTO  ipsweep.
264396  tcp    domain   REJ  ipsweep.
264413  tcp    gopher   REJ  ipsweep.

[100 rows x 4 columns]

Tiếp theo chúng ta tạo ma trận n x n để lưu trữ độ đo tương đồng giữa các điểm, trong đó n là số dòng của dữ liệu (ở đây là 100 do đề bài). 
- `overlap_matrix` để lưu trữ số lượng thuộc tính giống nhau giữa các điểm.
- `inv_freq_matrix` để lưu trữ độ đo tương đồng dựa trên tần suất nghịch đảo của các giá trị thuộc tính.

In [56]:
n = len(df_100)
overlap_matrix = np.zeros((n, n))
inv_freq_matrix = np.zeros((n, n))

Tiếp theo ta tính độ tương đồng giữa các điểm trong tập dữ liệu với công thức tổng quát như sau:

$$\text{Sim}(\overline{X}, \overline{Y} ) = \sum_{i=1}^{d} w_i \cdot \text{S}(x_i, y_i)$$
Với
- $w_i = \frac{1}{d}$ với i = 1, 2, ..., d
- $S(x_i, y_i)$ là hàm đánh giá sự giống nhau giữa thuộc tính $i$ được chia làm 2 loại là độ đo Overlap và độ đo dựa trên tần suất xuất hiện ngược


Ta tính độ đo Overlap với công thức: 

$$\text{Overlap}(x_i, y_i) = \text{S}(x_i, y_i) = \begin{cases} 1 & \text{nếu } x_i = y_i \\ 0 & \text{nếu } x_i \neq y_i \end{cases}$$


Cụ thể với code như sau:
`d = len(X)` để lấy số lượng thuộc tính của điểm X (và Y do |X| = |Y|).

Tiếp theo ta tính độ đo Overlap giữa X và Y bằng cách đếm số lượng thuộc tính giống nhau giữa hai điểm và chia cho tổng số thuộc tính d như công thức tổng quát sau khi thay $S(x_i, y_i)$ bằng công thức Overlap:
```python
sum = 0
for i in range(d):
    if X[i] == Y[i]:
        sum += 1
return sum / d
```

In [57]:
def overlap(X, Y):
    d = len(X)
    sum = 0
    for i in range(d):
        if X[i] == Y[i]:
            sum += 1
    return sum / d

Tương tự ta tính độ đo dựa trên tần suất xuất hiện ngược với công thức:

$$\text{Invfreq}(x_i, y_i) = \text{S}(x_i, y_i) = \begin{cases} \frac{1}{1 + \text{log}(f_i(x_i)) \cdot \text{log}(f_i(y_i))} & \text{nếu } x_i = y_i \\ 0 & \text{nếu } x_i \neq y_i \end{cases}$$

Note: $log$ ở đây là log cơ số 10, và $f_i(x_i)$ là tần suất xuất hiện của giá trị $x_i$ trong thuộc tính $i$ của tập dữ liệu

Tạo một hàm riêng để đếm và lấy tần suất xuất hiện của các giá trị thuộc tính trong tập dữ liệu để có thể sử dụng trong hàm tính độ đo dựa trên tần suất xuất hiện ngược.
Bằng cách ta dùng kỹ thuật dictionary để lưu tên của thuộc tính và tần suất xuất hiện của các giá trị thuộc tính đó trong tập dữ liệu.

```python
    for i in range(d):
        unique, counts = np.unique(data[:, i], return_counts=True)
        freq_dict = {} 
        for j in range(len(unique)):
            keyname = unique[j]       
            value = counts[j] 
            freq_dict[keyname] = value        
        freqs.append(freq_dict)
    return freqs
```

`unique` là mảng chứa các giá trị duy nhất của thuộc tính i, `counts` là mảng chứa số lần xuất hiện của từng giá trị đó. Ta tạo một dictionary `freq_dict` để lưu trữ tần suất xuất hiện của từng giá trị, với key là giá trị và value là số lần xuất hiện. Sau đó ta thêm `freq_dict` vào list `freqs` để có thể sử dụng sau này trong hàm tính độ đo dựa trên tần suất xuất hiện ngược.

In [ ]:
def freq(data):
    data = data.values
    freqs = []
    d = data.shape[1]
    
    for i in range(d):
        unique, counts = np.unique(data[:, i], return_counts=True)
        freq_dict = {} 
        for j in range(len(unique)):
            keyname = unique[j]       
            value = counts[j] 
            freq_dict[keyname] = value        
        freqs.append(freq_dict)
    return freqs

Cuối cùng ta áp dụng công thức tính độ đo dựa trên tần suất xuất hiện ngược vào hàm `inv_freq` bằng cách thay $S(x_i, y_i)$ bằng công thức đã cho và sử dụng tần suất xuất hiện từ `freqs`

In [ ]:
def inv_freq(X, Y, freqs):
    d = len(X)
    sim = 0
    
    for i in range(d):
        if X[i] == Y[i]:
            f_x = freqs[i].get(X[i], 0)
            f_y = freqs[i].get(Y[i], 0)
            
            if f_x > 0 and f_y > 0:
                sim += 1 / (1 + (np.log(f_x) * np.log(f_y)))
    return sim / d

In [ ]:
freqs = freq(df_100)

for i in range(n):
    for j in range(n):
        if i == j:
            overlap_matrix[i, j] = 1.0 
            inv_freq_matrix[i, j] = 1.0
        else:
            overlap_matrix[i, j] = overlap(df_100.values[i], df_100.values[j])
            inv_freq_matrix[i, j] = inv_freq(df_100.values[i], df_100.values[j], freqs)

for i in range(n): 
    overlap_scores = overlap_matrix[i].copy()
    inv_freq_scores = inv_freq_matrix[i].copy()
    
    overlap_scores[i] = -1 
    inv_freq_scores[i] = -1
    
    best_overlap_idx = np.argmax(overlap_scores)
    best_inv_freq_idx = np.argmax(inv_freq_scores)
    
    print(f"\n df line {i}:")
    print(f" - Overlap ~= {best_overlap_idx}, v = {overlap_scores[best_overlap_idx]}")
    print(f" - Inverse freq ~= {best_inv_freq_idx}, v = {inv_freq_scores[best_inv_freq_idx]}")

[{'icmp': np.int64(5), 'tcp': np.int64(92), 'udp': np.int64(3)}, {'auth': np.int64(1), 'ctf': np.int64(2), 'daytime': np.int64(2), 'discard': np.int64(2), 'domain': np.int64(3), 'domain_u': np.int64(1), 'echo': np.int64(2), 'eco_i': np.int64(1), 'ecr_i': np.int64(3), 'finger': np.int64(3), 'ftp': np.int64(3), 'ftp_data': np.int64(6), 'gopher': np.int64(3), 'http': np.int64(9), 'link': np.int64(2), 'mtp': np.int64(3), 'name': np.int64(3), 'netstat': np.int64(2), 'ntp_u': np.int64(1), 'other': np.int64(2), 'pop_3': np.int64(1), 'private': np.int64(6), 'remote_job': np.int64(3), 'rje': np.int64(3), 'smtp': np.int64(6), 'ssh': np.int64(4), 'supdup': np.int64(1), 'systat': np.int64(2), 'telnet': np.int64(13), 'time': np.int64(3), 'urp_i': np.int64(1), 'whois': np.int64(3)}, {'OTH': np.int64(1), 'REJ': np.int64(25), 'RSTO': np.int64(15), 'RSTOS0': np.int64(5), 'RSTR': np.int64(12), 'S0': np.int64(6), 'S1': np.int64(4), 'S2': np.int64(1), 'S3': np.int64(3), 'SF': np.int64(28)}, {'buffer_overflow.': np.int64(1), 'guess_passwd.': np.int64(4), 'ipsweep.': np.int64(23), 'loadmodule.': np.int64(1), 'neptune.': np.int64(1), 'normal.': np.int64(27), 'perl.': np.int64(1), 'pod.': np.int64(1), 'portsweep.': np.int64(39), 'smurf.': np.int64(1), 'teardrop.': np.int64(1)}]

 df line 0:
 - Overlap ~= 1, v = 0.75
 - Inverse freq ~= 1, v = 0.07562948311289361

 df line 1:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 0, v = 0.07562948311289361

 df line 2:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 10, v = 0.11829495856778857

 df line 3:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 18, v = 0.09210837115928414

 df line 4:
 - Overlap ~= 12, v = 0.75
 - Inverse freq ~= 12, v = 0.15500833734913178

 df line 5:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 0, v = 0.05338665208965101

 df line 6:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 90, v = 0.1455904685833976

 df line 7:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 10, v = 0.06571765147285336

 df line 8:
 - Overlap ~= 13, v = 0.75
 - Inverse freq ~= 13, v = 0.11136202795077632

 df line 9:
 - Overlap ~= 7, v = 0.75
 - Inverse freq ~= 7, v = 0.06529794218240816

 df line 10:
 - Overlap ~= 2, v = 0.75
 - Inverse freq ~= 2, v = 0.11829495856778857

 df line 11:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 48, v = 0.12493543449189934

 df line 12:
 - Overlap ~= 4, v = 0.75
 - Inverse freq ~= 4, v = 0.15500833734913178

 df line 13:
 - Overlap ~= 8, v = 0.75
 - Inverse freq ~= 23, v = 0.20356584444452291

 df line 14:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 30, v = 0.1460101778738428

 df line 15:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 0, v = 0.07562948311289361

 df line 16:
 - Overlap ~= 31, v = 0.75
 - Inverse freq ~= 31, v = 0.201598848264613

 df line 17:
 - Overlap ~= 8, v = 0.75
 - Inverse freq ~= 8, v = 0.11136202795077632

 df line 18:
 - Overlap ~= 2, v = 0.75
 - Inverse freq ~= 2, v = 0.11829495856778857

 df line 19:
 - Overlap ~= 7, v = 0.75
 - Inverse freq ~= 34, v = 0.07464217889855139

 df line 20:
 - Overlap ~= 7, v = 0.75
 - Inverse freq ~= 7, v = 0.06529794218240816

 df line 21:
 - Overlap ~= 7, v = 0.75
 - Inverse freq ~= 7, v = 0.06529794218240816

 df line 22:
 - Overlap ~= 7, v = 0.5
 - Inverse freq ~= 24, v = 0.07103362777734068

 df line 23:
 - Overlap ~= 13, v = 0.75
 - Inverse freq ~= 13, v = 0.20356584444452291

 df line 24:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 67, v = 0.11393149289208154

 df line 25:
 - Overlap ~= 7, v = 0.75
 - Inverse freq ~= 33, v = 0.13020624866054573

 df line 26:
 - Overlap ~= 13, v = 0.75
 - Inverse freq ~= 13, v = 0.20356584444452291

 df line 27:
 - Overlap ~= 4, v = 0.5
 - Inverse freq ~= 4, v = 0.13393359396718832

 df line 28:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 0, v = 0.05338665208965101

 df line 29:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 30, v = 0.09210837115928414

 df line 30:
 - Overlap ~= 14, v = 0.75
 - Inverse freq ~= 14, v = 0.1460101778738428

 df line 31:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 16, v = 0.201598848264613

 df line 32:
 - Overlap ~= 2, v = 0.75
 - Inverse freq ~= 2, v = 0.11829495856778857

 df line 33:
 - Overlap ~= 25, v = 0.75
 - Inverse freq ~= 25, v = 0.13020624866054573

 df line 34:
 - Overlap ~= 19, v = 0.75
 - Inverse freq ~= 25, v = 0.13020624866054573

 df line 35:
 - Overlap ~= 25, v = 0.75
 - Inverse freq ~= 25, v = 0.13020624866054573

 df line 36:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 76, v = 0.0930384200100165

 df line 37:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 36, v = 0.08836863533449638

 df line 38:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 80, v = 0.0930384200100165

 df line 39:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 38, v = 0.08836863533449638

 df line 40:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 41, v = 0.19785911243982524

 df line 41:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 40, v = 0.19785911243982524

 df line 42:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 43, v = 0.19785911243982524

 df line 43:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 42, v = 0.19785911243982524

 df line 44:
 - Overlap ~= 47, v = 0.75
 - Inverse freq ~= 78, v = 0.1272194859934866

 df line 45:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 46, v = 0.19785911243982524

 df line 46:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 45, v = 0.19785911243982524

 df line 47:
 - Overlap ~= 19, v = 0.75
 - Inverse freq ~= 19, v = 0.07464217889855139

 df line 48:
 - Overlap ~= 44, v = 0.75
 - Inverse freq ~= 77, v = 0.15493470529954081

 df line 49:
 - Overlap ~= 44, v = 0.75
 - Inverse freq ~= 96, v = 0.10103289858498217

 df line 50:
 - Overlap ~= 44, v = 0.75
 - Inverse freq ~= 82, v = 0.15493470529954081

 df line 51:
 - Overlap ~= 38, v = 0.75
 - Inverse freq ~= 61, v = 0.09862413265069958

 df line 52:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 83, v = 0.14694022672457516

 df line 53:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 52, v = 0.14227044204905503

 df line 54:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 84, v = 0.14694022672457516

 df line 55:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 54, v = 0.14227044204905503

 df line 56:
 - Overlap ~= 44, v = 0.75
 - Inverse freq ~= 85, v = 0.12493543449189934

 df line 57:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 86, v = 0.14694022672457516

 df line 58:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 57, v = 0.14227044204905503

 df line 59:
 - Overlap ~= 44, v = 0.75
 - Inverse freq ~= 87, v = 0.12493543449189934

 df line 60:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 88, v = 0.14694022672457516

 df line 61:
 - Overlap ~= 51, v = 0.75
 - Inverse freq ~= 60, v = 0.14227044204905503

 df line 62:
 - Overlap ~= 51, v = 0.75
 - Inverse freq ~= 6, v = 0.12493543449189934

 df line 63:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 89, v = 0.14694022672457516

 df line 64:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 63, v = 0.14227044204905503

 df line 65:
 - Overlap ~= 51, v = 0.75
 - Inverse freq ~= 92, v = 0.18052410488266954

 df line 66:
 - Overlap ~= 38, v = 0.75
 - Inverse freq ~= 38, v = 0.08836863533449638

 df line 67:
 - Overlap ~= 24, v = 0.75
 - Inverse freq ~= 24, v = 0.11393149289208154

 df line 68:
 - Overlap ~= 51, v = 0.75
 - Inverse freq ~= 51, v = 0.09862413265069958

 df line 69:
 - Overlap ~= 66, v = 0.75
 - Inverse freq ~= 66, v = 0.08836863533449638

 df line 70:
 - Overlap ~= 66, v = 0.75
 - Inverse freq ~= 93, v = 0.18052410488266954

 df line 71:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 72, v = 0.19785911243982524

 df line 72:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 71, v = 0.19785911243982524

 df line 73:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 74, v = 0.19785911243982524

 df line 74:
 - Overlap ~= 37, v = 0.75
 - Inverse freq ~= 73, v = 0.19785911243982524

 df line 75:
 - Overlap ~= 0, v = 0.75
 - Inverse freq ~= 95, v = 0.11787524927734337

 df line 76:
 - Overlap ~= 36, v = 0.75
 - Inverse freq ~= 36, v = 0.0930384200100165

 df line 77:
 - Overlap ~= 48, v = 0.75
 - Inverse freq ~= 48, v = 0.15493470529954081

 df line 78:
 - Overlap ~= 44, v = 0.75
 - Inverse freq ~= 44, v = 0.1272194859934866

 df line 79:
 - Overlap ~= 19, v = 0.75
 - Inverse freq ~= 19, v = 0.07464217889855139

 df line 80:
 - Overlap ~= 38, v = 0.75
 - Inverse freq ~= 38, v = 0.0930384200100165

 df line 81:
 - Overlap ~= 3, v = 0.75
 - Inverse freq ~= 97, v = 0.09411483193159714

 df line 82:
 - Overlap ~= 50, v = 0.75
 - Inverse freq ~= 50, v = 0.15493470529954081

 df line 83:
 - Overlap ~= 52, v = 0.75
 - Inverse freq ~= 52, v = 0.14694022672457516

 df line 84:
 - Overlap ~= 54, v = 0.75
 - Inverse freq ~= 54, v = 0.14694022672457516

 df line 85:
 - Overlap ~= 81, v = 0.75
 - Inverse freq ~= 98, v = 0.1480166386461558

 df line 86:
 - Overlap ~= 57, v = 0.75
 - Inverse freq ~= 57, v = 0.14694022672457516

 df line 87:
 - Overlap ~= 81, v = 0.75
 - Inverse freq ~= 99, v = 0.1480166386461558

 df line 88:
 - Overlap ~= 60, v = 0.75
 - Inverse freq ~= 60, v = 0.14694022672457516

 df line 89:
 - Overlap ~= 63, v = 0.75
 - Inverse freq ~= 63, v = 0.14694022672457516

 df line 90:
 - Overlap ~= 6, v = 0.75
 - Inverse freq ~= 6, v = 0.1455904685833976

 df line 91:
 - Overlap ~= 76, v = 0.75
 - Inverse freq ~= 76, v = 0.05674287100314158

 df line 92:
 - Overlap ~= 76, v = 0.75
 - Inverse freq ~= 65, v = 0.18052410488266954

 df line 93:
 - Overlap ~= 76, v = 0.75
 - Inverse freq ~= 70, v = 0.18052410488266954

 df line 94:
 - Overlap ~= 81, v = 0.75
 - Inverse freq ~= 82, v = 0.1480166386461558

 df line 95:
 - Overlap ~= 75, v = 0.75
 - Inverse freq ~= 78, v = 0.12030141934010158

 df line 96:
 - Overlap ~= 3, v = 0.75
 - Inverse freq ~= 49, v = 0.10103289858498217

 df line 97:
 - Overlap ~= 49, v = 0.75
 - Inverse freq ~= 49, v = 0.10103289858498217

 df line 98:
 - Overlap ~= 76, v = 0.75
 - Inverse freq ~= 85, v = 0.1480166386461558

 df line 99:
 - Overlap ~= 76, v = 0.75
 - Inverse freq ~= 87, v = 0.1480166386461558